apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adminer-pvc
spec:
  accessModes:
    - ReadWriteOnce # Atau ReadWriteMany/ReadOnlyMany tergantung kebutuhan Adminer
  resources:
    requests:
      storage: 1Gi # Sesuaikan ukuran storage yang Anda butuhkan
  # storageClassName: # Opsional: Jika Anda ingin menggunakan StorageClass tertentu